---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: analytics.fegzyn1.mongodb.net
  mongo-username: analytics
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-password:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-viewer
  template:
    metadata:
      labels:
        app: mongo-viewer
    spec:
      containers:
        - name: mongo-viewer
          image: sundalei/mongo-viewer
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: mongo-url
                  name: mongo-config
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: mongo-username
                  name: mongo-config
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-viewer
spec:
  selector:
    app: mongo-viewer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080